In [1]:
import numpy as np
import opt_fellows_assigner as opt_fs
import swap_fellows_assigner 
import encrypt_function as enc
import encrypt_function_ddc_in_size
import psnr_function
import dcca_sketch_attack
import incc_sketch_attack
import eac_sketch_attack

In [2]:
image = 'lena'

In [8]:
# fellows by optimizations
lena_lambdath = 149847
opt_pairs = opt_fs.opt_fellows_assigner(lena_lambdath)
opt_msb0_fellows = opt_pairs[0]
opt_msb1_fellows = opt_pairs[1]

In [3]:
# fellows by swapping
x = +2
sH = 10
sw_pairs = swap_fellows_assigner.swap_fellows_assigner('lena', x, sH)
sw_msb0_fellows = sw_pairs[0]
sw_msb1_fellows = sw_pairs[1]

In [16]:
# encryption within BCopt with complete DC encryption
a = enc.encrypt_function(image, opt_msb0_fellows, opt_msb1_fellows)

In [18]:
# encryption within BCopt with dDC encryption within size
b = encrypt_function_ddc_in_size.encrypt_function(image, opt_msb0_fellows, opt_msb1_fellows)

In [12]:
# encryption within SwapBC
c = enc.encrypt_function(image, sw_msb0_fellows, sw_msb1_fellows)

In [20]:
# encryption within SwapBC with dDC encryption within size
d = encrypt_function_ddc_in_size.encrypt_function(image, sw_msb0_fellows, sw_msb1_fellows)

In [22]:
# numerical results
opt_psnr = psnr_function.get_psnr(image+'.tif', 'enc_lena_lamth.png')
opt_psnr_ddc_in_size = psnr_function.get_psnr(image+'.tif', 'enc_ddc_in_size_lena_lamth.png')
sw_psnr = psnr_function.get_psnr(image+'.tif', 'enc_lena_x2_sH10.png')
sw_psnr_ddc_in_size = psnr_function.get_psnr(image+'.tif', 'enc_ddc_in_size_lena_x2_sH10.png')

print(opt_psnr, opt_psnr_ddc_in_size, sw_psnr, sw_psnr_ddc_in_size)

6.991180459819666 5.523369574632653 6.775063304184065 5.338323155718495


In [4]:
#dcca sketch attack
dcca_sketch_attack.dcca_attack(image)

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       ...,
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.]])

In [5]:
#incc sketch attack
incc_sketch_attack.incc_attack(image)

array([[214., 214., 214., ..., 238., 238., 238.],
       [214., 214., 214., ..., 238., 238., 238.],
       [214., 214., 214., ..., 238., 238., 238.],
       ...,
       [230., 230., 230., ..., 242., 242., 242.],
       [230., 230., 230., ..., 242., 242., 242.],
       [230., 230., 230., ..., 242., 242., 242.]])

In [4]:
eac_sketch_attack.eac_attack(image, sw_msb0_fellows, sw_msb1_fellows)

array([[ 79.,  79.,  79., ..., 112., 112., 112.],
       [ 79.,  79.,  79., ..., 112., 112., 112.],
       [ 79.,  79.,  79., ..., 112., 112., 112.],
       ...,
       [ 27.,  27.,  27., ...,  85.,  85.,  85.],
       [ 27.,  27.,  27., ...,  85.,  85.,  85.],
       [ 27.,  27.,  27., ...,  85.,  85.,  85.]])